export const STATUS_UPDATE_LOADING = 'STATUS_UPDATE_LOADING';

export const SET_AUTHENTICATED = 'SET_AUTHENTICATED';

export const SET_SELECTED = 'SET_SELECTED';

export const SET_ROWS = 'SET_ROWS';

export const UPDATE_ROWS_STATUS = 'UPDATE_ROWS_STATUS';

export const SET_SHOW_SNACKBAR = 'SET_SHOW_SNACKBAR';